"""Package the entire project, environment specifications and optional references."""

import argparse
import hashlib
import json
import zipfile
from pathlib import Path

IGNORED = {'.git', '.venv', '__pycache__', '.pytest_cache', '.ruff_cache',
           'pytest-of-root', 'deliverables'}


def project_files(root):
    for path in root.rglob('*'):
        relative = path.relative_to(root)
        if any(part in IGNORED or part.endswith('.egg-info') for part in relative.parts):
            continue
        if len(relative.parts) == 1 and relative.name.startswith('tmp'):
            continue
        if path.is_file() and not path.is_symlink() and path.suffix not in ('.pyc', '.tmp'):
            yield relative, path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--sanet', type=Path)
    parser.add_argument('--icc-paper', type=Path)
    parser.add_argument('--sanet-paper', type=Path)
    parser.add_argument('--output', type=Path, default=Path('deliverables/icc_sanet_complete.zip'))
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    files = dict(project_files(root))
    if args.sanet:
        for relative, path in project_files(args.sanet):
            files[Path('reference/SANet') / relative] = path
    for title, path in (('ICC.pdf', args.icc_paper), ('SANet.pdf', args.sanet_paper)):
        if path is not None:
            files[Path('papers') / title] = path
    files.pop(Path('PACKAGE_MANIFEST.json'), None)
    manifest = {'package': 'icc_sanet_project', 'entrypoint': 'START_HERE.md',
                'scope': 'all source, data, experiments/checkpoints and environment specifications',
                'excluded': ['machine-specific virtualenv', 'VCS internal files',
                             'test/cache/generated bytecode directories',
                             'root temporary downloads', 'previous deliverables directory'],
                'dependencies': 'online rebuild from requirements/setup script; no binary environment included',
                'files': {}}
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(args.output, 'w', compression=zipfile.ZIP_DEFLATED,
                         compresslevel=6, allowZip64=True) as archive:
        for relative, path in sorted(files.items()):
            with path.open('rb') as handle:
                digest = hashlib.file_digest(handle, 'sha256').hexdigest()
            manifest['files'][relative.as_posix()] = {'bytes': path.stat().st_size,
                                                    'sha256': digest}
            archive.write(path, Path('icc_sanet_project') / relative)
        archive.writestr('icc_sanet_project/PACKAGE_MANIFEST.json',
                         json.dumps(manifest, indent=2, ensure_ascii=False) + '\n')
    print(f'{args.output.resolve()} — {args.output.stat().st_size / 1048576:.2f} MiB, '
          f'{len(files)} source/data/result files')


if __name__ == '__main__':
    main()
